#define DUNGEON_WIDTH 100
#define DUNGEON_HEIGHT 100
#define DUNGEON_GENERATOR_URL "http://127.0.0.1:8000"
#define DUNGEON_GENERATOR_TIMEOUT 300
#define DUNGEON_GENERATE_ENDPOINT "/generate_dungeon"
#define PORTAL_TRAIT_DUNGEON list(ZTRAIT_AWAY, ZTRAIT_MINING)
#define PORTAL_ACTIVE_POWER_USAGE (BASE_MACHINE_ACTIVE_CONSUMPTION * 2)
#define VEILBREAK_TEMP_MAP_PREFIX "data/veilbreak_temp_"
#define VEILBREAK_CLEANUP_BATCH_SIZE 50
#define VEILBREAK_MOB_SPAWN_BATCH_SIZE 25
#define VEILBREAK_TURF_PROCESS_BATCH_SIZE 50
#define VEILBREAK_VOID_CREATURE_BOSS_KILL_MULT 1.1
