// =================================================================
// OPTIC LIGHT BEAM PUZZLE SYSTEM
// =================================================================
// System introducing rotatable light emitters, splitter prisms,
// optic reflectors, and color-sensitive receivers.
// =================================================================

GLOBAL_LIST_EMPTY(optic_devices)

#define OPTIC_COLOR_RED     "red"
#define OPTIC_COLOR_GREEN   "green"
#define OPTIC_COLOR_BLUE    "blue"
#define OPTIC_COLOR_YELLOW  "yellow"
#define OPTIC_COLOR_MAGENTA "magenta"
#define OPTIC_COLOR_CYAN    "cyan"
#define OPTIC_COLOR_WHITE   "white"

/// Returns the hex color string corresponding to an optic color name
/proc/get_optic_hex_color(color_name)
	switch(color_name)
		if(OPTIC_COLOR_RED)
			return "#ff2222"
		if(OPTIC_COLOR_GREEN)
			return "#22ff22"
		if(OPTIC_COLOR_BLUE)
			return "#2266ff"
		if(OPTIC_COLOR_YELLOW)
			return "#ffff22"
		if(OPTIC_COLOR_MAGENTA)
			return "#ff22ff"
		if(OPTIC_COLOR_CYAN)
			return "#22ffff"
		if(OPTIC_COLOR_WHITE)
			return "#ffffff"
	return "#ffffff"

/// Combines a list of primary/secondary colors into a resultant additive color
/proc/mix_optic_colors(list/colors)
	if(!length(colors))
		return null
	var/has_red = FALSE
	var/has_green = FALSE
	var/has_blue = FALSE

	for(var/C in colors)
		switch(C)
			if(OPTIC_COLOR_RED)
				has_red = TRUE
			if(OPTIC_COLOR_GREEN)
				has_green = TRUE
			if(OPTIC_COLOR_BLUE)
				has_blue = TRUE
			if(OPTIC_COLOR_YELLOW)
				has_red = TRUE
				has_green = TRUE
			if(OPTIC_COLOR_MAGENTA)
				has_red = TRUE
				has_blue = TRUE
			if(OPTIC_COLOR_CYAN)
				has_green = TRUE
				has_blue = TRUE
			if(OPTIC_COLOR_WHITE)
				has_red = TRUE
				has_green = TRUE
				has_blue = TRUE

	if(has_red && has_green && has_blue)
		return OPTIC_COLOR_WHITE
	if(has_red && has_green)
		return OPTIC_COLOR_YELLOW
	if(has_red && has_blue)
		return OPTIC_COLOR_MAGENTA
	if(has_green && has_blue)
		return OPTIC_COLOR_CYAN
	if(has_red)
		return OPTIC_COLOR_RED
	if(has_green)
		return OPTIC_COLOR_GREEN
	if(has_blue)
		return OPTIC_COLOR_BLUE
	return null

// ================= ================= =================
// BASE OPTIC PUZZLE STRUCTURE
// ================= ================= =================

/obj/structure/optic_base
	name = "optic device"
	desc = "A mechanical optical device that can be rotated."
	icon = 'icons/obj/structures.dmi'
	icon_state = "reflector"
	density = TRUE
	anchored = TRUE
	/// Rotation angle in degrees (0-360)
	var/rotation_angle = 0
	/// Whether rotation is enabled
	var/can_rotate = TRUE
	/// Whether this device can be unanchored with a wrench
	var/can_unanchor = FALSE
	/// Active visual beam datums generated by this device
	var/list/datum/beam/active_beams = list()
	/// List of colors received during current beam tick cycle
	var/list/received_colors = list()

/obj/structure/optic_base/Initialize(mapload)
	. = ..()
	GLOB.optic_devices += src
	set_angle(rotation_angle)

/obj/structure/optic_base/Destroy()
	GLOB.optic_devices -= src
	clear_optic_beams()
	return ..()

/// Clears all currently active beam visual datums created by this device
/obj/structure/optic_base/proc/clear_optic_beams()
	for(var/datum/beam/B in active_beams)
		qdel(B)
	active_beams.Cut()

/// Sets the rotation angle and applies visual transform
/obj/structure/optic_base/proc/set_angle(new_angle)
	rotation_angle = SIMPLIFY_DEGREES(new_angle)
	dir = angle2dir(rotation_angle)
	var/matrix/M = matrix()
	var/dir_angle = (icon == 'modular_zzveilbreak/icons/obj/voidlaser.dmi') ? dir2angle(dir) : 0
	M.Turn(SIMPLIFY_DEGREES(rotation_angle - dir_angle))
	transform = M

/// Opens the 360-degree rotation prompt matching standard reflectors
/obj/structure/optic_base/proc/rotate(mob/user)
	if(!can_rotate)
		to_chat(user, span_warning("[src]'s rotation is locked!"))
		return FALSE
	var/new_angle = tgui_input_number(user, "New angle for [src.name] (0-360 degrees)", "[src.name] Angle", rotation_angle, 360)
	if(isnull(new_angle) || QDELETED(user) || QDELETED(src) || !user.can_perform_action(src, FORBID_TELEKINESIS_REACH))
		return FALSE
	set_angle(new_angle)
	to_chat(user, span_notice("You rotate [src] to [rotation_angle]°."))
	return TRUE

/obj/structure/optic_base/interact(mob/user)
	rotate(user)

/obj/structure/optic_base/attack_hand(mob/user, list/modifiers)
	. = ..()
	if(.)
		return
	rotate(user)

/obj/structure/optic_base/examine(mob/user)
	. = ..()
	. += span_notice("It is angled at <b>[rotation_angle]°</b>. Interact with it to rotate it 360 degrees.")
	if(can_unanchor)
		. += span_notice("It is <b>[anchored ? "anchored" : "unanchored"]</b>. Use a wrench to [anchored ? "unanchor" : "anchor"] it.")

/obj/structure/optic_base/add_context(atom/source, list/context, obj/item/held_item, mob/user)
	. = ..()
	if(can_unanchor && held_item?.tool_behaviour == TOOL_WRENCH)
		context[SCREENTIP_CONTEXT_LMB] = "[anchored ? "Unanchor" : "Anchor"]"
		return TRUE

/obj/structure/optic_base/wrench_act(mob/living/user, obj/item/tool)
	. = ..()
	if(!can_unanchor)
		balloon_alert(user, "permanently anchored!")
		return ITEM_INTERACT_BLOCKING
	if(tool.use_tool(src, user, 1 SECONDS, volume = 50))
		set_anchored(!anchored)
		user.balloon_alert_to_viewers("[anchored ? "anchored" : "unanchored"]")
		to_chat(user, span_notice("You [anchored ? "anchor" : "unanchor"] [src]."))
		if(!anchored)
			clear_optic_beams()
		update_all_optic_beams()
		return ITEM_INTERACT_SUCCESS

/obj/structure/optic_base/Moved(atom/old_loc, movement_dir, forced, list/old_locs)
	. = ..()
	clear_optic_beams()
	update_all_optic_beams()

/// Base handler called when an optic beam hits this object
/obj/structure/optic_base/proc/receive_optic_beam(color_name, incoming_angle, list/visited)
	return

/// Traces a light beam from start_turf along beam_angle
/obj/structure/optic_base/proc/trace_beam(turf/start_turf, color_name, beam_angle, max_range = 15, list/visited = list())
	if(!start_turf || max_range <= 0 || !anchored)
		return

	var/step_dir = angle2dir(beam_angle)
	if(!step_dir)
		return

	var/turf/curr_turf = start_turf
	var/turf/last_turf = start_turf

	for(var/i in 1 to max_range)
		var/turf/next_turf = get_step(curr_turf, step_dir)
		if(!next_turf || next_turf.density)
			break

		last_turf = next_turf
		curr_turf = next_turf

		// Check for optic puzzle structures on next_turf
		var/obj/structure/optic_base/target_optic = locate() in next_turf
		if(target_optic)
			if(!target_optic.anchored)
				break
			if(visited[target_optic])
				break
			visited[target_optic] = TRUE
			draw_beam_segment(start_turf, next_turf, color_name)
			target_optic.receive_optic_beam(color_name, beam_angle, visited)
			return

	draw_beam_segment(start_turf, last_turf, color_name)

/// Renders a visual beam segment between start and end turfs
/obj/structure/optic_base/proc/draw_beam_segment(turf/start_turf, turf/end_turf, color_name)
	if(!start_turf || !end_turf || start_turf == end_turf)
		return
	var/datum/beam/B = start_turf.Beam(
		end_turf,
		icon_state = "light_beam",
		time = 2 SECONDS,
		beam_color = get_optic_hex_color(color_name)
	)
	if(B)
		active_beams += B

// ================= ================= =================
// CONTINUOUS WHITE LIGHT EMITTER
// ================= ================= =================

/obj/structure/optic_base/emitter
	name = "optic white light emitter"
	desc = "A heavy optical device that outputs a continuous beam of white light. Can be rotated 360 degrees."
	icon = 'modular_zzveilbreak/icons/obj/voidlaser.dmi'
	icon_state = "vemitter"
	/// Whether the emitter is powered on
	var/active = TRUE

/obj/structure/optic_base/emitter/Initialize(mapload)
	. = ..()
	START_PROCESSING(SSobj, src)

/obj/structure/optic_base/emitter/Destroy()
	STOP_PROCESSING(SSobj, src)
	return ..()

/obj/structure/optic_base/emitter/set_angle(new_angle)
	. = ..()
	update_all_optic_beams()

/obj/structure/optic_base/emitter/process(seconds_between_ticks)
	if(active && anchored)
		update_all_optic_beams()

/obj/structure/optic_base/emitter/proc/update_emitter_beams()
	update_all_optic_beams()

/// Global proc to update all optical beams and receiver states in the world
/proc/update_all_optic_beams()
	for(var/obj/structure/optic_base/O in GLOB.optic_devices)
		O.clear_optic_beams()
		O.received_colors.Cut()

	for(var/obj/structure/optic_base/emitter/E in GLOB.optic_devices)
		if(E.active && E.anchored)
			var/turf/start_turf = get_turf(E)
			if(start_turf)
				var/list/visited = list()
				visited[E] = TRUE
				E.trace_beam(start_turf, OPTIC_COLOR_WHITE, E.rotation_angle, 15, visited)

	for(var/obj/structure/optic_base/receiver/R in GLOB.optic_devices)
		R.check_receiver_state()

// ================= ================= =================
// SPLITTER PRISM
// ================= ================= =================

/obj/structure/optic_base/prism
	name = "splitter prism"
	desc = "A crystalline prism that refracts light. Splits white light into red, green, and blue beams. Can be rotated 360 degrees."
	icon = 'icons/obj/structures.dmi'
	icon_state = "reflector"
	color = "#e0ffff"

/obj/structure/optic_base/prism/set_angle(new_angle)
	. = ..()
	update_all_optic_beams()

/obj/structure/optic_base/prism/receive_optic_beam(color_name, incoming_angle, list/visited)
	var/turf/start_turf = get_turf(src)
	if(!start_turf || !anchored)
		return

	if(color_name in received_colors)
		return
	received_colors |= color_name

	clear_optic_beams()

	var/has_red = FALSE
	var/has_green = FALSE
	var/has_blue = FALSE

	for(var/C in received_colors)
		switch(C)
			if(OPTIC_COLOR_RED)
				has_red = TRUE
			if(OPTIC_COLOR_GREEN)
				has_green = TRUE
			if(OPTIC_COLOR_BLUE)
				has_blue = TRUE
			if(OPTIC_COLOR_YELLOW)
				has_red = TRUE
				has_green = TRUE
			if(OPTIC_COLOR_MAGENTA)
				has_red = TRUE
				has_blue = TRUE
			if(OPTIC_COLOR_CYAN)
				has_green = TRUE
				has_blue = TRUE
			if(OPTIC_COLOR_WHITE)
				has_red = TRUE
				has_green = TRUE
				has_blue = TRUE

	var/list/new_visited = visited ? visited.Copy() : list()
	new_visited[src] = TRUE

	if(has_red)
		trace_beam(start_turf, OPTIC_COLOR_RED, rotation_angle, 15, new_visited.Copy())
	if(has_green)
		trace_beam(start_turf, OPTIC_COLOR_GREEN, SIMPLIFY_DEGREES(rotation_angle - 45), 15, new_visited.Copy())
	if(has_blue)
		trace_beam(start_turf, OPTIC_COLOR_BLUE, SIMPLIFY_DEGREES(rotation_angle + 45), 15, new_visited.Copy())

// ================= ================= =================
// OPTIC REFLECTOR BOX (MIRROR)
// ================= ================= =================

/obj/structure/optic_base/reflector
	name = "optic reflector box"
	desc = "A box with an internal set of mirrors that reflects all light beams out in the direction it is facing. Can be rotated 360 degrees."
	icon = 'icons/obj/structures.dmi'
	icon_state = "reflector_box"

/obj/structure/optic_base/reflector/set_angle(new_angle)
	. = ..()
	update_all_optic_beams()

/obj/structure/optic_base/reflector/receive_optic_beam(color_name, incoming_angle, list/visited)
	var/turf/start_turf = get_turf(src)
	if(!start_turf || !anchored)
		return

	if(color_name in received_colors)
		return
	received_colors |= color_name

	clear_optic_beams()

	var/mixed_color = mix_optic_colors(received_colors)
	if(mixed_color)
		var/list/new_visited = visited ? visited.Copy() : list()
		new_visited[src] = TRUE
		trace_beam(start_turf, mixed_color, rotation_angle, 15, new_visited)

// ================= ================= =================
// LIGHT RECEIVER
// ================= ================= =================

/obj/structure/optic_base/receiver
	name = "optic light receiver"
	desc = "A photosensitive receiver that detects light colors and activates when its requested color combination is received."
	icon = 'modular_zzveilbreak/icons/obj/voidlaser.dmi'
	icon_state = "vreceiver"
	/// Color required to activate the receiver (editable via View Variables table)
	var/required_color = null
	/// Active state
	var/active = FALSE
	/// Receivers cannot be rotated manually
	can_rotate = FALSE
	/// Linked door to trigger when active
	var/obj/machinery/door/linked_door
	/// Search radius for auto-linking doors
	var/door_search_range = 7

/obj/structure/optic_base/receiver/Initialize(mapload)
	if(!required_color)
		required_color = pick(list(OPTIC_COLOR_RED, OPTIC_COLOR_GREEN, OPTIC_COLOR_BLUE, OPTIC_COLOR_YELLOW, OPTIC_COLOR_MAGENTA, OPTIC_COLOR_CYAN, OPTIC_COLOR_WHITE))
	. = ..()
	START_PROCESSING(SSobj, src)
	get_linked_door()

/obj/structure/optic_base/receiver/Destroy()
	STOP_PROCESSING(SSobj, src)
	return ..()

/// Locates and caches the nearest door within range
/obj/structure/optic_base/receiver/proc/get_linked_door()
	if(linked_door && !QDELETED(linked_door))
		return linked_door

	var/obj/machinery/door/best_door = null
	var/best_dist = INFINITY

	for(var/obj/machinery/door/D in range(door_search_range, src))
		var/dist = get_dist(src, D)
		if(dist < best_dist)
			best_dist = dist
			best_door = D

	linked_door = best_door
	return linked_door

/obj/structure/optic_base/receiver/examine(mob/user)
	. = ..()
	. += span_notice("It is configured to require <b>[required_color]</b> light. Currently: <b>[active ? "ACTIVE" : "INACTIVE"]</b>.")

/obj/structure/optic_base/receiver/interact(mob/user)
	return

/obj/structure/optic_base/receiver/attack_hand(mob/user, list/modifiers)
	return

/obj/structure/optic_base/receiver/screwdriver_act(mob/living/user, obj/item/tool)
	return ITEM_INTERACT_BLOCKING

/obj/structure/optic_base/receiver/receive_optic_beam(color_name, incoming_angle, list/visited)
	received_colors |= color_name

/// Evaluates received colors against requested color and opens/closes linked door
/obj/structure/optic_base/receiver/proc/check_receiver_state()
	var/mixed_color = mix_optic_colors(received_colors)
	var/obj/machinery/door/target_door = get_linked_door()

	if(mixed_color == required_color)
		if(!active)
			active = TRUE
			set_light(2, 1, get_optic_hex_color(required_color))
			playsound(src, 'sound/effects/phasein.ogg', 40, TRUE)
			to_chat(range(5, src), span_boldnotice("[src] activates as it receives [required_color] light!"))
		if(target_door && !QDELETED(target_door))
			target_door.autoclose = FALSE
			if(target_door.density)
				INVOKE_ASYNC(target_door, TYPE_PROC_REF(/obj/machinery/door, open))
	else
		if(active)
			active = FALSE
			set_light(0)
			if(target_door && !QDELETED(target_door))
				target_door.autoclose = initial(target_door.autoclose)
				if(!target_door.density)
					INVOKE_ASYNC(target_door, TYPE_PROC_REF(/obj/machinery/door, close))

/obj/structure/optic_base/receiver/process(seconds_between_ticks)
	return
