name: "Discord PR Notification"

on:
  pull_request_target:
    types: [opened, closed, labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'Stale' }}
    steps:
      - name: "Check for PR_BOT secret"
        id: secrets_set
        env:
          ENABLER_SECRET: ${{ secrets.PR_BOT }}
        run: |
          if [ -n "$ENABLER_SECRET" ]; then
            echo "SECRETS_ENABLED=true" >> $GITHUB_OUTPUT
          else
            echo "SECRETS_ENABLED=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Discord notification
        uses: tgstation/discord-notify@v3
        if: steps.secrets_set.outputs.SECRETS_ENABLED == 'true'
        with:
          webhook_url: ${{ secrets.PR_BOT }}
          title: ${{ github.event.pull_request.user.login }} - ${{ github.event.pull_request.title }}
          message: |
            ${{
              github.event.action == 'opened' && '🚀 **Pull request opened**' ||
              github.event.action == 'closed' && (github.event.pull_request.merged && '✅ **Pull request merged**' || '❌ **Pull request closed without merge**') ||
              github.event.action == 'labeled' && format('🏷️ **Pull request #{0} marked as stale**', github.event.pull_request.number)
            }}
          include_image: false
          show_author: false
          avatar_url: "https://avatars.githubusercontent.com/u/240644724?s=200&v=4"
          username: "PocketFox"
          title_url: "${{ github.event.pull_request.html_url }}"
