name: 'Upstream Sync'

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:
    inputs:
      sync_test_mode:
        description: 'Test mode (dry run)'
        type: boolean
        default: false

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync with upstream repository

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        uses: qoomon/actions--setup-git@v1
        with:
          user: 'bot'

      - name: Sync upstream-updates with master
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git checkout -B upstream-updates
          git push -f origin upstream-updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          target_sync_branch: upstream-updates
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: SPLURT-Station/S.P.L.U.R.T-tg   # <-- only change here
          test_mode: ${{ inputs.sync_test_mode }}

      - name: Get current date
        if: steps.sync.outputs.has_new_commits == 'true'
        run: |
          echo "NOW=$(date +%d.%m.%Y)" >> $GITHUB_ENV   # fixed syntax (was $env:GITHUB_ENV)

      - name: Create Pull Request
        if: steps.sync.outputs.has_new_commits == 'true'
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: "upstream-updates"
          destination_branch: "master"
          pr_title: "[UPSTREAM SYNC - SPLURT] ${{ env.NOW }}"
          pr_body: "Upstream update from SPLURT-Station/S.P.L.U.R.T-tg as of ${{ env.NOW }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found and synced."

      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "No new commits to sync."
